// ─── 콜렉션 데이터 ────────────────────────────────────────────────────────────
const COLLECTION_DATA = {
    normal: [
        { id: 'w_hammer', cat: '무기',   emoji: '🔨', name: '뿅망치',      unlocked: true  },
        { id: 'w_gun',    cat: '무기',   emoji: '🔫', name: '물총',        unlocked: true},
        { id: 'w_lightning', cat: '무기',   emoji: '⚡', name: '번개',        unlocked: true},
        { id: 'w_bomb',      cat: '무기',   emoji: '💣', name: '폭탄',        unlocked: true},
        { id: 'w_balloon',   cat: '무기',   emoji: '🎈', name: '물풍선',      unlocked: true},
        { id: 'w_spotlight', cat: '무기',   emoji: '🔦', name: '핀조명',      unlocked: true},
        { id: 'w_ufo',       cat: '무기',   emoji: '🛸', name: 'UFO빔',       unlocked: true},
        { id: 'w_target',    cat: '무기',   emoji: '🎯', name: '타겟',        unlocked: true},
        { id: 'w_claw',      cat: '무기',   emoji: '🦾', name: '인형뽑기',    unlocked: true},
        { id: 't_field',  cat: '테마',   emoji: '🌿', name: '들판 테마',   unlocked: true  },
        { id: 't_snow',   cat: '테마',   emoji: '❄️', name: '설원 테마',   unlocked: true},
        { id: 't_night',  cat: '테마',   emoji: '🌙', name: '야간 테마',   unlocked: true},
        { id: 's_brown',  cat: '스킨',   emoji: '🟤', name: '기본 갈색',   unlocked: true  },
        { id: 's_gray',   cat: '스킨',   emoji: '⬜', name: '회색 두더지', unlocked: true},
        { id: 's_orange', cat: '스킨',   emoji: '🟠', name: '주황 두더지', unlocked: true},
        { id: 'h_cap',    cat: '모자',   emoji: '🧢', name: '야구모자',    unlocked: true},
        { id: 'h_tophat', cat: '모자',   emoji: '🎩', name: '실크햇',      unlocked: true},
        { id: 'pin-ribbon1',  cat: '모자',   emoji: '🎀', name: '리본 삔',     unlocked: true},
        { id: 'tie-ribbon1',  cat: '모자',   emoji: '🪢', name: '보타이',      unlocked: true},
        { id: 'headset',  cat: '모자',   emoji: '🎧', name: '헤드셋',      unlocked: true},
        { id: 'crown1',   cat: '모자',   emoji: '👑', name: '왕관',        unlocked: true},
        { id: 'g_spy',    cat: '안경',   emoji: '🕶️', name: '클래식 선글', unlocked: true  },
        { id: 'g_round',  cat: '안경',   emoji: '👓', name: '동글 안경',   unlocked: true},
        { id: 'a_tie',    cat: '장신구', emoji: '👔', name: '넥타이',      unlocked: true},
        { id: 'a_star',   cat: '장신구', emoji: '⭐', name: '별 브로치',   unlocked: true},
        { id: 'e_water',  cat: '효과',   emoji: '💧', name: '물방울',      unlocked: true  },
        { id: 'e_spark',  cat: '효과',   emoji: '✨', name: '별빛',        unlocked: true},
    ],
    hidden: [
        { id: 'hw_gold',    cat: '무기',   emoji: '🌟', name: '황금 물총',     unlocked: true},
        { id: 'hh_skull',   cat: '모자',   emoji: '💀', name: '해골 모자',     unlocked: true},
        { id: 'hg_vip',     cat: '안경',   emoji: '🕶️', name: 'VIP 선글라스',  unlocked: true},
        { id: 'ha_diamond', cat: '장신구', emoji: '💎', name: '다이아 브로치', unlocked: true},
        { id: 'he_rainbow', cat: '효과',   emoji: '🌈', name: '무지개 이펙트', unlocked: true},
    ],
};
